[package]
name = "cascada"
description = "A general purpose UI layout engine"
version = "0.1.0"
authors = ["Wakunguma Kalimukwa <wakunguma13@gmail.com>"]
license = "Apache-2.0 OR MIT"
edition = "2024"
repository = "https://github.com/snubwoody/cascada"
categories = ["gui"]
keywords = ["gui", "graphics","ui"]

[dependencies]
agape_core = "0.3.0"
thiserror = "2.0.9"

[workspace.lints.clippy]
enum_glob_use = "warn"
branches_sharing_code = "warn"
