name: Upload libraries
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
concurrency:
  group: upload-libraries
  cancel-in-progress: false
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        name: Checkout repository
      - name: Build library
        run: cargo build --release --features ffi
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lib-${{ matrix.os }}
          path: |
            target/release/libcascada.so
            target/release/libcascada.dylib
            target/release/cascada.dll